### add department 
POST http://localhost:3000/addDept
Content-Type:application/json

{
    "name":"demo",
    "location":"demo"
}

### show Depts
GET http://localhost:3000/showDepts

###Edit department
PUT http://localhost:3000/updateDept/6ab4bd6dc3e32fbbd898b383
Content-Type:application/json

{
    "name":"demo1",
    "location":"demo1"
}

### delete department
DELETE http://localhost:3000/deleteDept/6ab4bd6dc3e32fbbd898b383

### add employee
POST http://localhost:3000/addEmployee
Content-Type:application/json

{   
    "salary":"5000",
    "department":"6ab4b7e36c1252e42922db9f"
}

### show employees
GET http://localhost:3000/showEmployees

### get employee by id
GET http://localhost:3000/employee/6575

###updateEmployee
PUT http://localhost:3000/updateEmployee/6ab4ba166c1252e42922dba0
Content-Type:application/json   

{
    "name":"John Doe",
    "salary":"8000"
}

#### delete employee
DELETE http://localhost:3000/deleteEmployee/6ab4bf7de748750b35234b6f


###show high salary employees
GET http://localhost:3000/highSalaryEmployees?salary=5000

### firstHighEarner
GET http://localhost:3000/firstHighEarner?salary=9000


###Show employee names
GET http://localhost:3000/employeeNames


#### add attendance
POST http://localhost:3000/addAttendance
Content-Type:application/json

{
     "employee":"6ab4ba496c1252e42922dba1",
    "date":"2026-09-27",
    "status":"Present"
}

#### show attendance
GET http://localhost:3000/showAttendance?status=Absent



#### update attendance
PUT http://localhost:3000/updateAttendance/6ab58eadac2dc676b9b9e356
Content-Type:application/json       

{
    "employee":"6ab4ba166c1252e42922dba0",
    "date":"2026-09-24",
    "status":"Absent"
}

#### delete attendance
DELETE http://localhost:3000/deleteAttendance/6ab58eadac2dc676b9b9e356

#### show attendance by employee
GET http://localhost:3000/showAttendanceByEmployee/6ab4ba496c1252e42922dba1

### show employee names
GET http://localhost:3000/employeeNames